version: '3'
services:
    web:
      image: nginx
      ports:
        - 80:80
      volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d

      networks:
        - nginxphp

    php:
      image: php 
      volumes:
        - ./public_html:/public_html
      expose:
          - 9000
      networks:
        - nginxphp     

networks:
  nginxphp:           